name: figma_client
description: A Figma API wrapper library for interacting with Figma documents,
  written in pure Dart.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  copy_with_extension: ^5.0.0
  equatable: ^2.0.5
  http: ^1.0.0
  http2: ^2.0.1
  json_annotation: ^4.8.0

dev_dependencies:
  args: ^2.4.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  json_serializable: ^6.6.1
  markdown: ^7.0.0
  test: ^1.23.1
  very_good_analysis: ^5.0.0
  yaml: ^3.1.1
