# Add this config at the end of your pubspec.yaml file.

figma_importer:
  api_token: your-figma-token
  file_id: vwGXt85mtTCPI5qP8ItIKj
  node_ids: [49823-12141]
  output_directory_path: lib/resources
  style_class_configs:
    - style: color
      class_name: Palette
    - style: typography
      class_name: TextStyles
    - style: shadows
      class_name: Shadows
  theme_class_config:
    class_name: MyAppTheme
    output_directory_path: lib/theme